apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: auth-api
  name: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: auth-api
    spec:
      containers:
        - env:
            - name: DB_DB
              value: alie_db
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db-host
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-pass
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db-port
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db-user
            - name: PORT
              value: "80"
            - name: SECRET
              value: setsecretink8ssecretforprod
          image: harbor.alie.javeriana.edu.co/images/auth-api:latest
          name: auth-api
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "1500m"
              memory: "1024Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always
