apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: auth-api
  name: auth-api
spec:
  ports:
    - name: "2001"
      port: 2001
      targetPort: 80
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: auth-api
