apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.cronjob.schedule: '*/30 * * * *'
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: db-init
  name: db-init
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            io.kompose.service: db-init
        spec:
          containers:
            - image: db-init
              name: db-init
          restartPolicy: OnFailure
  schedule: '*/30 * * * *'
