apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.cronjob.schedule: 0 7 * * *
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: db-init
  name: db-init
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            io.kompose.service: db-init
        spec:
          containers:
            - image: harbor.alie.javeriana.edu.co/images/db-init:latest
              name: db-init
              env:
                - name: COCKROACHDB_USER
                  valueFrom:
                    configMapKeyRef:
                      name: db-config
                      key: db-user
                - name: COCKROACHDB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: db-creds
                      key: db-pass
                - name: COCKROACHDB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: db-config
                      key: db-host
                - name: COCKROACHDB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: db-config
                      key: db-port
          restartPolicy: OnFailure
  schedule: 0 7 * * *
