apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: alie-ia
  name: alie-ia
spec:
  type: ExternalName
  externalName: alie-api.alie-ia.svc.cluster.local
  selector:
    io.kompose.service: alie-ia
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
